# /backend/modules/content_creator/steps.py
"""Content creation steps for the four active prompts."""

from pydantic import BaseModel, Field

from modules.flow_engine.public import AudioStep, ImageStep, StructuredStep, UnstructuredStep


# ---------- 1) Generate Unit Source Material ----------
class GenerateUnitSourceMaterialStep(UnstructuredStep):
    """Generate comprehensive source material for a unit from learner context.

    Output is plain-text with markdown headings as described in the prompt.
    Accepts learner_desires (unified context) instead of separate topic/learner_level.
    """

    step_name = "generate_source_material"
    prompt_file = "generate_source_material.md"
    reasoning_effort = "low"
    verbosity = "low"
    model = "gemini-2.5-flash"

    class Inputs(BaseModel):
        learner_desires: str
        target_lesson_count: int | None = None


class GenerateSupplementalSourceMaterialStep(UnstructuredStep):
    """Generate supplemental source material for uncovered learning objectives."""

    step_name = "generate_supplemental_source_material"
    prompt_file = "generate_supplemental_source_material.md"
    reasoning_effort = "low"
    verbosity = "low"
    model = "gemini-2.5-flash"

    class Inputs(BaseModel):
        learner_desires: str
        target_lesson_count: int | None = None
        objectives_outline: str


# ---------- 2) Extract Unit Metadata ----------
class UnitLearningObjective(BaseModel):
    id: str
    title: str | None = None
    description: str | None = None
    bloom_level: str | None = None
    evidence_of_mastery: str | None = None

    class Config:
        populate_by_name = True  # Allow both field name and alias

    def __init__(self, **data: dict) -> None:
        # For backward compatibility: map old field names to current names
        # Old prompts may return 'lo_id' → 'id' or 'text' → 'description'
        if "lo_id" in data and "id" not in data:
            data["id"] = data.pop("lo_id")
        if "text" in data and "description" not in data:
            data["description"] = data.pop("text")
        super().__init__(**data)


class LessonPlanItem(BaseModel):
    title: str
    lesson_objective: str
    learning_objective_ids: list[str]


class ExtractUnitMetadataStep(StructuredStep):
    """Extract unit-level metadata and ordered lesson plan as strict JSON.

    Uses coach-provided learning objectives directly (no regeneration).
    Focuses on generating lesson plan that covers all coach LOs.
    """

    step_name = "extract_unit_metadata"
    prompt_file = "extract_unit_metadata.md"
    reasoning_effort = "low"
    model = "gemini-2.5-flash"
    verbosity = "low"

    class Inputs(BaseModel):
        learner_desires: str
        coach_learning_objectives: list[dict]
        target_lesson_count: int | None = None
        source_material: str

    class Outputs(BaseModel):
        unit_title: str
        # NOTE: Lesson plan only; LOs come directly from coach (not regenerated)
        learning_objectives: list[UnitLearningObjective] = []
        lessons: list[LessonPlanItem]
        lesson_count: int


# ---------- 3) Lesson Podcast & Assessment Steps ----------
class GenerateLessonPodcastTranscriptStep(UnstructuredStep):
    """Generate an instructional podcast transcript for a single lesson."""

    step_name = "generate_lesson_podcast_transcript"
    prompt_file = "generate_lesson_podcast_transcript_instructional.md"
    reasoning_effort = "medium"
    verbosity = "low"
    model = "gemini-2.5-flash"

    class Inputs(BaseModel):
        learner_desires: str
        lesson_title: str
        lesson_objective: str
        learning_objectives: list[dict] = Field(default_factory=list)
        source_material: str
        sibling_lessons: list[dict] = Field(default_factory=list)
        lesson_number: int | None = None
        voice: str | None = None


class GenerateMCQsUnstructuredStep(UnstructuredStep):
    """Draft ten MCQs (5 comprehension, 5 transfer) prior to validation."""

    step_name = "generate_mcqs_unstructured"
    prompt_file = "generate_mcqs_unstructured.md"
    reasoning_effort = "high"
    verbosity = "low"
    model = "gemini-2.5-flash"

    class Inputs(BaseModel):
        learner_desires: str
        lesson_objective: str
        learning_objectives: list[dict] = Field(default_factory=list)
        sibling_lessons: list[dict] = Field(default_factory=list)
        podcast_transcript: str
        source_material: str


class MCQOption(BaseModel):
    label: str
    text: str
    rationale_wrong: str | None = None


class MCQAnswerKey(BaseModel):
    label: str
    rationale_right: str | None = None


class StructuredMCQExercise(BaseModel):
    id: str = Field(default="")  # Generated by backend if empty
    exercise_type: str = Field(default="mcq")  # Always "mcq"
    exercise_category: str
    aligned_learning_objective: str
    cognitive_level: str
    difficulty: str
    thinking: str | None = None  # LLM's reasoning about the question quality
    stem: str
    options: list[MCQOption] = Field(default_factory=list)
    answer_key: MCQAnswerKey


class MCQValidationOutputs(BaseModel):
    reasoning: str
    exercises: list[StructuredMCQExercise] = Field(default_factory=list)


class ValidateAndStructureMCQsStep(StructuredStep):
    """Validate MCQs and return structured quiz artifacts."""

    step_name = "validate_and_structure_mcqs"
    prompt_file = "validate_and_structure_mcqs.md"
    reasoning_effort = "medium"
    verbosity = "low"
    model = "gemini-2.5-flash"

    class Inputs(BaseModel):
        unstructured_mcqs: str
        podcast_transcript: str
        learning_objectives: list[dict] = Field(default_factory=list)

    class Outputs(MCQValidationOutputs):
        pass


# ---------- 5) Generate Unit Podcast Transcript ----------
class PodcastLessonInput(BaseModel):
    title: str
    podcast_transcript: str


class GenerateUnitPodcastTranscriptStep(UnstructuredStep):
    """Generate an intro-style podcast transcript that teases the full unit."""

    step_name = "generate_unit_podcast_transcript"
    prompt_file = "generate_intro_podcast_transcript.md"
    reasoning_effort = "medium"
    verbosity = "low"
    model = "gemini-2.5-flash"

    class Inputs(BaseModel):
        learner_desires: str
        unit_title: str
        voice: str
        unit_summary: str
        lessons: list[PodcastLessonInput]


class SynthesizePodcastAudioStep(AudioStep):
    """Synthesize narrated audio for the generated podcast transcript."""

    step_name = "synthesize_unit_podcast_audio"

    class Inputs(BaseModel):
        text: str
        voice: str
        model: str = "tts-1-hd"
        format: str = "mp3"
        speed: float | None = None


# ---------- 6) Generate Unit Art ----------
class GenerateUnitArtDescriptionStep(StructuredStep):
    """Produce a Weimar Edge styled art prompt for a learning unit."""

    step_name = "generate_unit_art_description"
    prompt_file = "unit_art_description.md"
    reasoning_effort = "medium"
    model = "gemini-2.5-flash"
    verbosity = "low"

    class Inputs(BaseModel):
        learner_desires: str
        unit_title: str
        unit_description: str | None = None
        learning_objectives: str = ""
        key_concepts: str = ""

    class Outputs(BaseModel):
        prompt: str
        alt_text: str
        palette: list[str]


class GenerateUnitArtImageStep(ImageStep):
    """Generate a hero image for the unit using the crafted prompt."""

    step_name = "generate_unit_art_image"

    class Inputs(BaseModel):
        prompt: str
        size: str = "256x256"
        quality: str = "standard"
        style: str | None = "natural"
