# render.yaml — Lantern Room on Render (native runtimes)

databases:
  - name: lantern-room-db
    plan: starter
    region: oregon

services:
  # FastAPI backend — Native Python
  - type: web
    name: lantern-room-backend
    runtime: python
    region: oregon
    plan: starter
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    preDeployCommand: alembic upgrade head
    startCommand: alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/v1/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: INFO
      - key: BASE_URL_HOST
        fromService:
          type: web
          name: lantern-room-admin
          property: host
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: S3_REGION
        value: us-west-1
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: FROM_EMAIL
        value: noreply@lanternroom.app
      - key: FROM_NAME
        value: Lantern Room
      - key: DATABASE_URL
        fromDatabase:
          name: lantern-room-db
          property: connectionString

  # Next.js Admin frontend — Native Node
  - type: web
    name: lantern-room-admin
    runtime: node
    region: oregon
    plan: starter
    rootDir: admin
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start -- -p $PORT
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 23.1.0
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_HOST
        fromService:
          type: web
          name: lantern-room-backend
          property: host
      - key: NEXT_PUBLIC_API_URL_SUFFIX
        value: /api/v1
