"""Initial migration

Revision ID: 39e90f55425b
Revises:
Create Date: 2025-07-14 11:06:52.102075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e90f55425b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bite_sized_topics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('core_concept', sa.String(), nullable=False),
    sa.Column('user_level', sa.String(), nullable=False),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.Column('key_concepts', sa.JSON(), nullable=True),
    sa.Column('key_aspects', sa.JSON(), nullable=True),
    sa.Column('target_insights', sa.JSON(), nullable=True),
    sa.Column('common_misconceptions', sa.JSON(), nullable=True),
    sa.Column('previous_topics', sa.JSON(), nullable=True),
    sa.Column('creation_strategy', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bite_sized_topics_core_concept', 'bite_sized_topics', ['core_concept'], unique=False)
    op.create_index('idx_bite_sized_topics_creation_strategy', 'bite_sized_topics', ['creation_strategy'], unique=False)
    op.create_index('idx_bite_sized_topics_user_level', 'bite_sized_topics', ['user_level'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bite_sized_components',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('component_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('component_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['bite_sized_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bite_sized_components_topic_id', 'bite_sized_components', ['topic_id'], unique=False)
    op.create_index('idx_bite_sized_components_topic_type', 'bite_sized_components', ['topic_id', 'component_type'], unique=False)
    op.create_index('idx_bite_sized_components_type', 'bite_sized_components', ['component_type'], unique=False)
    op.create_table('learning_paths',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('topic_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('current_topic_index', sa.Integer(), nullable=True),
    sa.Column('estimated_total_hours', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('learning_path_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('bite_sized_topic_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_paused', sa.Boolean(), nullable=True),
    sa.Column('content_data', sa.JSON(), nullable=True),
    sa.Column('interaction_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('current_lesson_index', sa.Integer(), nullable=True),
    sa.Column('conversation_state', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_progress')
    op.drop_table('learning_sessions')
    op.drop_table('topics')
    op.drop_table('learning_paths')
    op.drop_index('idx_bite_sized_components_type', table_name='bite_sized_components')
    op.drop_index('idx_bite_sized_components_topic_type', table_name='bite_sized_components')
    op.drop_index('idx_bite_sized_components_topic_id', table_name='bite_sized_components')
    op.drop_table('bite_sized_components')
    op.drop_table('users')
    op.drop_index('idx_bite_sized_topics_user_level', table_name='bite_sized_topics')
    op.drop_index('idx_bite_sized_topics_creation_strategy', table_name='bite_sized_topics')
    op.drop_index('idx_bite_sized_topics_core_concept', table_name='bite_sized_topics')
    op.drop_table('bite_sized_topics')
    # ### end Alembic commands ###
