"""update_execution_mode_values

Revision ID: 3a87cbd33286
Revises: eeb77219bb87
Create Date: 2025-09-21 22:27:06.675354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a87cbd33286'
down_revision: Union[str, None] = 'eeb77219bb87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_units_status'), table_name='units')
    op.drop_index(op.f('ix_units_status_updated_at'), table_name='units')
    # ### end Alembic commands ###
    
    # Update execution_mode values from "background" to "arq"
    # This handles the migration from the old asyncio background execution to ARQ
    op.execute("UPDATE flow_runs SET execution_mode = 'arq' WHERE execution_mode = 'background'")


def downgrade() -> None:
    # Revert execution_mode values from "arq" back to "background"
    # This handles the rollback of the ARQ migration
    op.execute("UPDATE flow_runs SET execution_mode = 'background' WHERE execution_mode = 'arq'")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_units_status_updated_at'), 'units', ['status', 'updated_at'], unique=False)
    op.create_index(op.f('ix_units_status'), 'units', ['status'], unique=False)
    # ### end Alembic commands ###
