"""updated_at

Revision ID: 4e6f5c9f9003
Revises: a711dff613e7
Create Date: 2025-09-13 16:14:19.104459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e6f5c9f9003'
down_revision: Union[str, None] = 'a711dff613e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_runs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('flow_step_runs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('llm_requests', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_requests', 'updated_at')
    op.drop_column('flow_step_runs', 'updated_at')
    op.drop_column('flow_runs', 'updated_at')
    # ### end Alembic commands ###
