"""add_podcast_tables_only

Revision ID: 6c8be4ad7cda
Revises: 681fa84808c7
Create Date: 2025-08-04 19:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c8be4ad7cda'
down_revision: Union[str, None] = '681fa84808c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'podcast_episodes',
        sa.Column('id', sa.VARCHAR(), nullable=False),
        sa.Column('title', sa.VARCHAR(), nullable=False),
        sa.Column('description', sa.TEXT(), nullable=True),
        sa.Column('learning_outcomes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('total_duration_minutes', sa.INTEGER(), nullable=False),
        sa.Column('full_script', sa.TEXT(), nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
        sa.Column('version', sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('podcast_episodes_pkey'))
    )
    op.create_index(op.f('idx_podcast_episodes_title'), 'podcast_episodes', ['title'], unique=False)
    op.create_index(op.f('idx_podcast_episodes_duration'), 'podcast_episodes', ['total_duration_minutes'], unique=False)

    op.create_table(
        'podcast_segments',
        sa.Column('id', sa.VARCHAR(), nullable=False),
        sa.Column('episode_id', sa.VARCHAR(), nullable=False),
        sa.Column('segment_type', sa.VARCHAR(), nullable=False),
        sa.Column('title', sa.VARCHAR(), nullable=False),
        sa.Column('script_content', sa.TEXT(), nullable=False),
        sa.Column('estimated_duration_seconds', sa.INTEGER(), nullable=False),
        sa.Column('order_index', sa.INTEGER(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
        sa.Column('version', sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(['episode_id'], ['podcast_episodes.id'], name=op.f('podcast_segments_episode_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('podcast_segments_pkey'))
    )
    op.create_index(op.f('idx_podcast_segments_episode_id'), 'podcast_segments', ['episode_id'], unique=False)
    op.create_index(op.f('idx_podcast_segments_type'), 'podcast_segments', ['segment_type'], unique=False)
    op.create_index(op.f('idx_podcast_segments_order'), 'podcast_segments', ['episode_id', 'order_index'], unique=False)

    op.create_table(
        'topic_podcast_links',
        sa.Column('id', sa.VARCHAR(), nullable=False),
        sa.Column('topic_id', sa.VARCHAR(), nullable=False),
        sa.Column('podcast_id', sa.VARCHAR(), nullable=False),
        sa.Column('is_primary_topic', sa.BOOLEAN(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(['podcast_id'], ['podcast_episodes.id'], name=op.f('topic_podcast_links_podcast_id_fkey')),
        sa.ForeignKeyConstraint(['topic_id'], ['bite_sized_topics.id'], name=op.f('topic_podcast_links_topic_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('topic_podcast_links_pkey'))
    )
    op.create_index(op.f('idx_topic_podcast_links_topic_id'), 'topic_podcast_links', ['topic_id'], unique=False)
    op.create_index(op.f('idx_topic_podcast_links_podcast_id'), 'topic_podcast_links', ['podcast_id'], unique=False)
    op.create_index(op.f('idx_topic_podcast_links_primary'), 'topic_podcast_links', ['podcast_id', 'is_primary_topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_topic_podcast_links_primary'), table_name='topic_podcast_links')
    op.drop_index(op.f('idx_topic_podcast_links_podcast_id'), table_name='topic_podcast_links')
    op.drop_index(op.f('idx_topic_podcast_links_topic_id'), table_name='topic_podcast_links')
    op.drop_table('topic_podcast_links')
    op.drop_index(op.f('idx_podcast_segments_order'), table_name='podcast_segments')
    op.drop_index(op.f('idx_podcast_segments_type'), table_name='podcast_segments')
    op.drop_index(op.f('idx_podcast_segments_episode_id'), table_name='podcast_segments')
    op.drop_table('podcast_segments')
    op.drop_index(op.f('idx_podcast_episodes_duration'), table_name='podcast_episodes')
    op.drop_index(op.f('idx_podcast_episodes_title'), table_name='podcast_episodes')
    op.drop_table('podcast_episodes')
    # ### end Alembic commands ###
