"""learning_session_tables

Revision ID: 74ac07d821d4
Revises: 413c509df009
Create Date: 2025-09-09 15:19:40.636378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ac07d821d4'
down_revision: Union[str, None] = '413c509df009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('current_component_index', sa.Integer(), nullable=False),
    sa.Column('total_components', sa.Integer(), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('session_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_sessions_status'), 'learning_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_learning_sessions_topic_id'), 'learning_sessions', ['topic_id'], unique=False)
    op.create_index(op.f('ix_learning_sessions_user_id'), 'learning_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_sessions_user_id'), table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_topic_id'), table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_status'), table_name='learning_sessions')
    op.drop_table('learning_sessions')
    # ### end Alembic commands ###
