"""add_flow_type_to_units

Revision ID: 7a2c9d1e5b10
Revises: e3bdc04203e4
Create Date: 2025-09-21 00:00:00.000000

"""
# mypy: ignore-errors
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a2c9d1e5b10'
down_revision: Union[str, None] = 'e3bdc04203e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('flow_type', sa.String(length=20), nullable=False, server_default='standard'))
    # Ensure future inserts use application default by dropping server_default after population if needed
    op.alter_column('units', 'flow_type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'flow_type')
    # ### end Alembic commands ###
