"""Change names

Revision ID: 928e1eb38cd0
Revises: 4e6f5c9f9003
Create Date: 2025-09-15 15:15:52.841485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '928e1eb38cd0'
down_revision: Union[str, None] = '4e6f5c9f9003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_sessions', sa.Column('current_exercise_index', sa.Integer(), nullable=False))
    op.add_column('learning_sessions', sa.Column('total_exercises', sa.Integer(), nullable=False))
    op.add_column('learning_sessions', sa.Column('exercises_completed', sa.Integer(), nullable=False))
    op.add_column('learning_sessions', sa.Column('exercises_correct', sa.Integer(), nullable=False))
    op.drop_column('learning_sessions', 'total_components')
    op.drop_column('learning_sessions', 'current_component_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_sessions', sa.Column('current_component_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('learning_sessions', sa.Column('total_components', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('learning_sessions', 'exercises_correct')
    op.drop_column('learning_sessions', 'exercises_completed')
    op.drop_column('learning_sessions', 'total_exercises')
    op.drop_column('learning_sessions', 'current_exercise_index')
    # ### end Alembic commands ###
