"""initial_schema

Revision ID: 9cb0b78b0c16
Revises: 
Create Date: 2025-10-24 20:58:32.719603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb0b78b0c16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('flow_name', sa.String(length=100), nullable=False),
    sa.Column('arq_task_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('execution_mode', sa.String(length=20), nullable=False),
    sa.Column('current_step', sa.String(length=200), nullable=True),
    sa.Column('step_progress', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('flow_metadata', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_runs_arq_task_id'), 'flow_runs', ['arq_task_id'], unique=False)
    op.create_index(op.f('ix_flow_runs_flow_name'), 'flow_runs', ['flow_name'], unique=False)
    op.create_index(op.f('ix_flow_runs_status'), 'flow_runs', ['status'], unique=False)
    op.create_index(op.f('ix_flow_runs_user_id'), 'flow_runs', ['user_id'], unique=False)
    op.create_table('learning_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('unit_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('current_exercise_index', sa.Integer(), nullable=False),
    sa.Column('total_exercises', sa.Integer(), nullable=False),
    sa.Column('exercises_completed', sa.Integer(), nullable=False),
    sa.Column('exercises_correct', sa.Integer(), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('session_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_sessions_lesson_id'), 'learning_sessions', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_learning_sessions_status'), 'learning_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_learning_sessions_unit_id'), 'learning_sessions', ['unit_id'], unique=False)
    op.create_index(op.f('ix_learning_sessions_user_id'), 'learning_sessions', ['user_id'], unique=False)
    op.create_table('llm_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('api_variant', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('provider_response_id', sa.String(length=100), nullable=True),
    sa.Column('system_fingerprint', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('additional_params', sa.JSON(), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_content', sa.Text(), nullable=True),
    sa.Column('response_raw', sa.JSON(), nullable=True),
    sa.Column('response_output', sa.JSON(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('response_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('retry_attempt', sa.Integer(), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_requests_api_variant'), 'llm_requests', ['api_variant'], unique=False)
    op.create_index(op.f('ix_llm_requests_cached'), 'llm_requests', ['cached'], unique=False)
    op.create_index(op.f('ix_llm_requests_model'), 'llm_requests', ['model'], unique=False)
    op.create_index(op.f('ix_llm_requests_provider'), 'llm_requests', ['provider'], unique=False)
    op.create_index(op.f('ix_llm_requests_provider_response_id'), 'llm_requests', ['provider_response_id'], unique=False)
    op.create_index(op.f('ix_llm_requests_status'), 'llm_requests', ['status'], unique=False)
    op.create_index(op.f('ix_llm_requests_user_id'), 'llm_requests', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('queue_name', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=255), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('current_step', sa.String(length=200), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('flow_run_id', sa.UUID(), nullable=True),
    sa.Column('unit_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_flow_run_id'), 'tasks', ['flow_run_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_name'), 'tasks', ['task_name'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_tasks_unit_id'), 'tasks', ['unit_id'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('s3_bucket', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('bitrate_kbps', sa.Integer(), nullable=True),
    sa.Column('sample_rate_hz', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audios_s3_key', 'audios', ['s3_key'], unique=True)
    op.create_index('ix_audios_user_id', 'audios', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('conversation_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('conversation_metadata', sa.JSON(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_conversation_type'), 'conversations', ['conversation_type'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('flow_step_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flow_run_id', sa.UUID(), nullable=False),
    sa.Column('llm_request_id', sa.UUID(), nullable=True),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('step_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['flow_run_id'], ['flow_runs.id'], ),
    sa.ForeignKeyConstraint(['llm_request_id'], ['llm_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_step_runs_flow_run_id'), 'flow_step_runs', ['flow_run_id'], unique=False)
    op.create_index(op.f('ix_flow_step_runs_llm_request_id'), 'flow_step_runs', ['llm_request_id'], unique=False)
    op.create_index(op.f('ix_flow_step_runs_status'), 'flow_step_runs', ['status'], unique=False)
    op.create_index(op.f('ix_flow_step_runs_step_name'), 'flow_step_runs', ['step_name'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('s3_bucket', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_images_s3_key', 'images', ['s3_key'], unique=True)
    op.create_index('ix_images_user_id', 'images', ['user_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('llm_request_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_order', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['llm_request_id'], ['llm_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_llm_request_id'), 'conversation_messages', ['llm_request_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_role'), 'conversation_messages', ['role'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('learner_level', sa.String(length=50), nullable=False),
    sa.Column('lesson_order', sa.JSON(), nullable=False),
    sa.Column('arq_task_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.Column('target_lesson_count', sa.Integer(), nullable=True),
    sa.Column('source_material', sa.Text(), nullable=True),
    sa.Column('generated_from_topic', sa.Boolean(), nullable=False),
    sa.Column('flow_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('creation_progress', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('podcast_transcript', sa.Text(), nullable=True),
    sa.Column('podcast_voice', sa.String(length=100), nullable=True),
    sa.Column('podcast_audio_object_id', sa.UUID(), nullable=True),
    sa.Column('podcast_generated_at', sa.DateTime(), nullable=True),
    sa.Column('art_image_id', sa.UUID(), nullable=True),
    sa.Column('art_image_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'in_progress', 'completed', 'failed')", name='check_unit_status'),
    sa.ForeignKeyConstraint(['art_image_id'], ['images.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_arq_task_id'), 'units', ['arq_task_id'], unique=False)
    op.create_index(op.f('ix_units_art_image_id'), 'units', ['art_image_id'], unique=False)
    op.create_index(op.f('ix_units_user_id'), 'units', ['user_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('learner_level', sa.String(length=50), nullable=False),
    sa.Column('source_material', sa.Text(), nullable=True),
    sa.Column('package', sa.JSON(), nullable=False),
    sa.Column('package_version', sa.Integer(), nullable=False),
    sa.Column('flow_run_id', sa.UUID(), nullable=True),
    sa.Column('unit_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flow_run_id'], ['flow_runs.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_flow_run_id'), 'lessons', ['flow_run_id'], unique=False)
    op.create_index(op.f('ix_lessons_unit_id'), 'lessons', ['unit_id'], unique=False)
    op.create_table('unit_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unit_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('last_lesson_id', sa.String(), nullable=True),
    sa.Column('completed_lesson_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_sessions_status'), 'unit_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_unit_sessions_unit_id'), 'unit_sessions', ['unit_id'], unique=False)
    op.create_index(op.f('ix_unit_sessions_user_id'), 'unit_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_sessions_user_id'), table_name='unit_sessions')
    op.drop_index(op.f('ix_unit_sessions_unit_id'), table_name='unit_sessions')
    op.drop_index(op.f('ix_unit_sessions_status'), table_name='unit_sessions')
    op.drop_table('unit_sessions')
    op.drop_index(op.f('ix_lessons_unit_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_flow_run_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_units_user_id'), table_name='units')
    op.drop_index(op.f('ix_units_art_image_id'), table_name='units')
    op.drop_index(op.f('ix_units_arq_task_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_conversation_messages_role'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_llm_request_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index('ix_images_user_id', table_name='images')
    op.drop_index('ix_images_s3_key', table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_flow_step_runs_step_name'), table_name='flow_step_runs')
    op.drop_index(op.f('ix_flow_step_runs_status'), table_name='flow_step_runs')
    op.drop_index(op.f('ix_flow_step_runs_llm_request_id'), table_name='flow_step_runs')
    op.drop_index(op.f('ix_flow_step_runs_flow_run_id'), table_name='flow_step_runs')
    op.drop_table('flow_step_runs')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_conversation_type'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_audios_user_id', table_name='audios')
    op.drop_index('ix_audios_s3_key', table_name='audios')
    op.drop_table('audios')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_unit_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_name'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_flow_run_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_llm_requests_user_id'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_status'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_provider_response_id'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_provider'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_model'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_cached'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_api_variant'), table_name='llm_requests')
    op.drop_table('llm_requests')
    op.drop_index(op.f('ix_learning_sessions_user_id'), table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_unit_id'), table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_status'), table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_lesson_id'), table_name='learning_sessions')
    op.drop_table('learning_sessions')
    op.drop_index(op.f('ix_flow_runs_user_id'), table_name='flow_runs')
    op.drop_index(op.f('ix_flow_runs_status'), table_name='flow_runs')
    op.drop_index(op.f('ix_flow_runs_flow_name'), table_name='flow_runs')
    op.drop_index(op.f('ix_flow_runs_arq_task_id'), table_name='flow_runs')
    op.drop_table('flow_runs')
    # ### end Alembic commands ###
