"""Link lesson to flow run

Revision ID: a711dff613e7
Revises: 9661888248d9
Create Date: 2025-09-13 15:51:49.997332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a711dff613e7'
down_revision: Union[str, None] = '9661888248d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('flow_run_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_lessons_flow_run_id'), 'lessons', ['flow_run_id'], unique=False)
    op.create_foreign_key(None, 'lessons', 'flow_runs', ['flow_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_index(op.f('ix_lessons_flow_run_id'), table_name='lessons')
    op.drop_column('lessons', 'flow_run_id')
    # ### end Alembic commands ###
