"""art

Revision ID: ae6b1da8a7a2
Revises: 3e2bd904a2f4
Create Date: 2025-09-30 16:20:18.614350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6b1da8a7a2'
down_revision: Union[str, None] = '3e2bd904a2f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_units_art_image_id'), table_name='units')
    op.create_index(op.f('ix_units_art_image_id'), 'units', ['art_image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_units_art_image_id'), table_name='units')
    op.create_index(op.f('idx_units_art_image_id'), 'units', ['art_image_id'], unique=False)
    # ### end Alembic commands ###
