"""add_unit_creation_status

Revision ID: eeb77219bb87
Revises: 7a2c9d1e5b10
Create Date: 2025-09-21 09:50:00.824490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb77219bb87'
down_revision: Union[str, None] = '7a2c9d1e5b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('status', sa.String(length=20), nullable=False, server_default="completed"))
    op.add_column('units', sa.Column('creation_progress', sa.JSON(), nullable=True))
    op.add_column('units', sa.Column('error_message', sa.Text(), nullable=True))
    
    # Add check constraint for status enum
    op.create_check_constraint(
        'check_unit_status',
        'units',
        "status IN ('draft', 'in_progress', 'completed', 'failed')"
    )
    
    # Add indexes for efficient queries
    op.create_index('ix_units_status', 'units', ['status'])
    op.create_index('ix_units_status_updated_at', 'units', ['status', 'updated_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes first
    op.drop_index('ix_units_status_updated_at', 'units')
    op.drop_index('ix_units_status', 'units')
    
    # Drop check constraint
    op.drop_constraint('check_unit_status', 'units')
    
    # Drop columns
    op.drop_column('units', 'error_message')
    op.drop_column('units', 'creation_progress')
    op.drop_column('units', 'status')
    # ### end Alembic commands ###
